name: Docker Image CI

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: 'registry.cn-shanghai.aliyuncs.com/fanyuanhang'
  # github.repository as <account>/<repo>
  IMAGE_NAME: rancher

on:
  push:
    branches: [ "cfel-release/v2.8" ]
  pull_request:
    branches: [ "cfel-release/v2.8" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # GitHub Actions的工作目录通常是通过 actions/checkout 步骤获取的
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Show Dir
      run: |
       pwd
       echo "GitHub Actions workspace: ${{ github.workspace }}"
       ls "${{ github.workspace }}/docker"
    # 执行 go mod vendor
    - name: Vendor dependencies
      run: go mod vendor
    # 修改指定文件
    - name: Modify cache.go
      run: |
        sed -i '39s/X-Frame-Options", "SAMEORIGIN"/X-Frame-Options", "ALLOWALL"/' vendor/github.com/rancher/apiserver/pkg/middleware/cache.go
    # 登录  
    # 登录  
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    # 执行构建命令
    - name: Build Docker image
      run: |
        TARGET_REPO="rancher-local:v2.8.0" dev-scripts/build-local.sh
    # 推送
    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker tag rancher-local:v2.8.0 "${{ env.REGISTRY }}/fanyuanhang/${{ env.IMAGE_NAME }}:v2.8.0.1"
        docker push "${{ env.REGISTRY }}/fanyuanhang/${{ env.IMAGE_NAME }}:v2.8.0.1"
